Forgot to wrap proto as assembly, caused error:
ValueError: arguments without labels along dimension 'presentation' cannot be aligned because they have different dimension sizes: {24320, 23040, 21760, 21120}

which was a red herring;  it's because you can't align if it's not indexed, and I hadn't done gather_indexes.

Calculated NaNs for tests.