package Ko's hvm assembly (#3)
* package Ko's hvm data

* Merge branch 'ko-hvm' of C:\Users\Martin\workspaces\dicarlo\mkgu_packaging with conflicts.

* package Rajalingham objectome behavioral responses and stimuli

separated in: all, partial_trials (public fit), full_trials (private test)

* remove filepaths; name all_stimuli

* use absolute data paths to where data is currently stored

* add sample_obj and label metadata to StimulusSet

* Lookup populator functions and naming setup.

* A draft of the Rajalingham script with lookup and file writing added.

* Getting an error:
ValueError: unsupported dtype for netCDF4 variable: bool

* Fixed S3 key, fixed error from "correct" coordinate, added upload.

* Generalize packaging (#10)

* Basic tests for packaging methods.

* Updated notebook for generating test images and metadata.

* Remove index from CSV.

* Tests not passing.

* test_add_image_metadata_to_db() now passes, but does not adequately test new record insertion.

* test_add_image_metadata_to_db now passes and genuinely tests new record insertion in attributemodel, imagemodel, imagemetamodel, imagestoremodel, imagestoremap, stimulussetmodel, stimulussetimagemap.

* test_package_stimulus_set not yet passing, may need to revert lookup.db before running tests.

* More assertions in test_package_stimulus_set.

* Rolling back the test additions to the database with a fixture.  Now all the tests can run.  Adding Travis yml.

* Trying to trigger a build.

* Make it installable for Travis.

* Still trying to make it installable...

* Added AWS keys.

* First draft of assembly packaging, not yet tested.

* package Kar2019 OST (#8)

* Basic tests for packaging methods.

* Updated notebook for generating test images and metadata.

* Remove index from CSV.

* Tests not passing.

* package Kar2019 OST (without upload)

* include i1 measures

* test_add_image_metadata_to_db() now passes, but does not adequately test new record insertion.

* align metadata with expected coords from metrics

* add logistic OSTs to SVM OSTs

* test_add_image_metadata_to_db now passes and genuinely tests new record insertion in attributemodel, imagemodel, imagemetamodel, imagestoremodel, imagestoremap, stimulussetmodel, stimulussetimagemap.

* test_package_stimulus_set not yet passing, may need to revert lookup.db before running tests.

* More assertions in test_package_stimulus_set.

* Rolling back the test additions to the database with a fixture.  Now all the tests can run.  Adding Travis yml.

* Trying to trigger a build.

* Make it installable for Travis.

* Still trying to make it installable...

* Added AWS keys.

* First draft of assembly packaging, not yet tested.

* use new generic packaging

* fix uding `write_netcdf` sha1 return value

* fix using string path

* mark `test_package_stimulus_set` as requiring private access

* use pytest.mark instead of pytest.config

* Added Darren 10 ms neural responses (#12)

* Added darren function calls

* Added dldata dependency

* Removed dependency on dldata

* package assembly

* add logging, progress bar for s3 upload; set brainio-contrib default bucket

* package_assembly with packaging script